### ISSUE TITLE
Put some thought into the service worker caching strategies

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-preact-pwa#2]
See https://github.com/Esri/offline-editor-js/wiki/Working-with-Application-Cache for ideas

Map tiles?
JSAPI modules?

@andygup any thoughts (or even better, PRs!) are welcome!

**Comment by andygup** [comment]
Hey @tomwayson I have a few thoughts for consideration. Not sure if or when I might be able to take a stab at this.

- Service workers are great if you know for certain your users will only be using the application on browsers that support service workers. Currently that list excludes Edge and Safari. A decent portion of the offline field data collection apps I've been seen are run on laptops/tablets. Reference: http://caniuse.com/#search=service  

- App Cache is still the best way to go for full cross-browser support

- Definitely caching JS API modules could be very useful from an application load performance viewpoint. 

- I/We don't currently have any plans to extend offline tiles capabilities to the ArcGIS JS API 4.x.

**Comment by nickpeihl** [comment]
You might check out the `runtimeCaching` parameter in sw-precache. You should be able to add the `init.js` and other files from the ArcGIS JS API to the service worker so they don't have to be retrieved from the server every time. You could even add a `urlPattern` [matching the basemap tiles](https://github.com/SJCGIS/PolarisJS/blob/master/gruntfile.js#L84) for slow (2G) connections. 

Browsers that don't support service workers will still fallback gracefully to the browser cache and http requests.
