### ISSUE TITLE
Live example not working

### ISSUE THREAD

**Issue by Biboba** [tomwayson/esri-preact-pwa#7]
Hello,

Live [url](https://esri-preact-pwa.now.sh/) is not working.
Following error is displayed : 404 deployment could not be found.

Thanks

**Comment by tomwayson** [comment]
I'm sorry I did not see this issue earlier, it is working for me:

![image](https://user-images.githubusercontent.com/662944/36578389-c7537e76-1811-11e8-9605-69752683f289.png)

Can you try again?

**Comment by Biboba** [comment]
Hi @tomwayson ,
Yes, it is now working.
Thanks !

**Comment by tomwayson** [comment]
Thanks!
